version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - DJANGO_ENV=development
    depends_on:
      - db
    
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      
  celery-beat:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A config beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  postgres_data:
